version: "2"

networks:
  my-net:
    driver: bridge

services:
  service-registry:
    image: ha-service-registry:latest
    container_name: service-registry
    cpuset: 0,1
    ports:
      - "8761:8761"
    networks:
      - my-net
    volumes:
      - ./configs/service-registry.yml:/config/service-registry.yml
  service:
    image: ha-service:latest
    cpuset: 2,3,4,5
    networks:
      - my-net
    volumes:
      - ./configs/service.yml:/config/service.yml
  gateway:
    image: ha-gateway:latest
    container_name: gateway
    cpuset: 6,7
    networks:
      - my-net
    ports:
      - "8080:8080"
    volumes:
      - ./configs/gateway.yml:/config/gateway.yml