sr:
  image: ha-service.register:latest
  ports: 
    - "8761:8761"
dispatcher_1:
  image: ha-dispatcher:latest
  links: 
    - sr
dispatcher_2:
  image: ha-dispatcher:latest
  links: 
    - sr
gateway:
  image: ha-gateway:latest
  ports:
    - "8080:8080"
  links:
    - sr