version: "2"

networks:
  my-net:
    driver: bridge

services:
  service-registry-a:
    image: ha-service-registry:latest
    container_name: service-registry-a
    ports:
      - "8761:8761"
    networks:
      - my-net
    volumes:
      - ./configs/service-registry-a.yml:/config/service-registry.yml
  service-registry-b:
    image: ha-service-registry:latest
    container_name: service-registry-b
    ports:
      - "8762:8761"
    networks:
      - my-net
    volumes:
      - ./configs/service-registry-b.yml:/config/service-registry.yml

  service-a:
    image: ha-service:latest
    container_name: service-a
    networks:
      - my-net
    volumes:
      - ./configs/service.yml:/config/service.yml
  service-b:
    image: ha-service:latest
    container_name: service-b
    networks:
      - my-net
    volumes:
      - ./configs/service.yml:/config/service.yml
  gateway-a:
    image: ha-gateway:latest
    container_name: gateway-a
    networks:
      - my-net
    ports:
      - "8080:8080"
    volumes:
      - ./configs/gateway.yml:/config/gateway.yml
  gateway-b:
    image: ha-gateway:latest
    container_name: gateway-b
    ports:
      - "8081:8080"
    networks:
      - my-net
    volumes:
      - ./configs/gateway.yml:/config/gateway.yml