spring:
  application:
    name: service

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-a:8761/eureka/,http://service-registry-b:8761/eureka/
  instance:
    preferIpAddress: true