server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://service-register-b:8761/eureka/
    server:
      enableSelfPreservation: false
  instance:
    hostname: service-register-a