spring:
  application:
    name: service-registry

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://service-registry-b:8761/eureka/
    server:
      enableSelfPreservation: false
  instance:
    hostname: service-registry-a